services:
  video-recording-app:
    image: video-recording-app
    container_name: video-recording-app
    env_file:
      - .env.local
    networks:
      - flow_net

networks:
  flow_net:
    external: true
